version: '2.2'

services:
  db:
    image: mysql:latest
    container_name: django_db
    command: mysqld --default-authentication-plugin=mysql_native_password --port=3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE:db_bithouse
      - MYSQL_USER:root
      - MYSQL_PASSWORD:root123
      - MYSQL_ROOT_PASSWORD:root123
    ports:
      - 3307:3306
    env_file:
      - .env


  server:
    build: .
    container_name: django_app
    image: django:app
    command: "python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - MYSQL_DATABASE:db_bithouse
      - MYSQL_USER:root
      - MYSQL_PASSWORD:root123
      - MYSQL_ROOT_PASSWORD:root123
    depends_on:
      - db
    links: 
      - db
    # env_file:
    #   - .env

volumes:
  mysql_data:
